yum install -y java-devel
yum install -y sharutils
yum install -y selinux-policy-devel
yum install -y cmake3
yum install -y fuse-devel
yum install -y gperftools-devel
yum install -y liboath-devel
yum install -y libxml2-devel
yum install -y python-devel
yum install -y snappy-devel
yum install -y valgrind-devel
yum install -y xfsprogs-devel
yum install -y xmlstarlet
yum install -y yasm
yum install -y libaio-devel
yum install -y libcurl-devel
yum install -y libcap-ng-devel
yum install -y libudev-devel
yum install -y libnl3-devel
yum install -y librdkafka-devel
yum install -y openssl-devel
yum install -y python2-Cython
yum install -y redhat-lsb-core
yum install -y python2-Cython
yum install -y python3-devel
yum install -y python-sphinx
yum install -y lz4-devel
yum install -y expat-devel
yum install -y ncurses-devel
yum install -y CUnit-devel
yum install -y python36-Cython
yum install -y python-prettytable
yum install -y lttng-ust-devel
yum install -y libbabeltrace-devel
yum install -y nss-devel 
yum install -y libibverbs-devel
yum install -y librdmacm-devel
yum install -y libblkid-devel
yum install -y leveldb-devel.x86_64
yum install -y librabbitmq-devel.x86_64
yum install -y gperf.x86_64
yum install -y openldap-devel
